/*
 ******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2021-10-29

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

 ******************************************************************************
 */

/* Includes */



#include <Platform_Types.h>


#define RCC_BASE	(0x40023800)
#define PORTA_BASE	(0x40020000)


#define RCC_AHB1ENR	*((volatile uint32 *)(RCC_BASE + 0x30))
#define PORTA_CRH	*((volatile uint32 *) (PORTA_BASE + 0))


typedef union
{
	uint32 allFields;

	 struct S_ODR
	{
		uint32 : 5;
		uint32 PA5 : 1;
	}S_ODR;
}ODR_t;

#define S_PORTA_ODR ((ODR_t *)(PORTA_BASE + 0x14))

int main(void)
{
	uint32 i = 0;

	//Enable GPIOA Clock
	RCC_AHB1ENR &=~(1<<0);
	RCC_AHB1ENR |=(1<<0);

	//set PA5 output mode
	PORTA_CRH &=~(3 << 10);
	PORTA_CRH |= (1<<10);

	while(1)
	{
		S_PORTA_ODR->S_ODR.PA5 = 1;
		for(i = 0 ; i < 1000000 ; i++);
		S_PORTA_ODR->S_ODR.PA5 = 0;
		for(i = 0 ; i < 1000000 ; i++);
	}

	return 0;
}
